export const mobileLayout = {
  hasDetail: {
    detailEntityLabel: "订单明细",
    detailInfoAreas: [
      {
        isShowFieldName: "",
        useEmptyJudgment: "false",
        useDeleteTips: "false",
        isSpread: "false",
        lastId: "",
        id: "infoAreadefault_drop",
        packUpDetail: false,
        rows: [
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "label",
                express: "",
                type: "reference",
                subjectType: "SUBJECT",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "subjectId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields: "label",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: [
                  {
                    fieldName: "childLength",
                    type: "int",
                    filterType: "AND",
                    value: 0,
                    operator: "=",
                  },
                  {
                    fieldName: "type",
                    type: "text",
                    filterType: "AND",
                    value: "SUBJECT",
                    operator: "=",
                  },
                ],
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "分类",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "Subject",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__bianma",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "productId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields:
                  "c__bianma,productName,c__guigexinghao,c__kucunshuliang",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: {
                  children: [],
                  filters: [
                    {
                      fieldName: "status",
                      type: "picklist",
                      filterType: "AND",
                      value: "0",
                      operator: "<>",
                    },
                  ],
                  type: "AND",
                },
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "产品编码",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "Product",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "text",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__guigexinghao",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 255,
                label: "规格型号",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express:
                  "{&quot;assignmentField&quot;:&quot;productId&quot;,&quot;queryField&quot;:&quot;c__bianma&quot;}",
                type: "queryAssignment",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__bianma",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 254,
                label: "编码",
                canCreate: true,
                rows: 3,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 2,
                express: "",
                type: "decimal",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "quantity",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "数量年限",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "数量",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 2,
                express: "",
                type: "decimal",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__beipinshu",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "备品数",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__danweiquancheng",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__jibendanwei",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields: "c__danweiquancheng",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: "",
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "基本单位",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "e__dw",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__danweiquancheng",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__baozhuangdanwei",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields: "c__danweiquancheng",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: "",
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "计量单位",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "e__dw",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 1,
                express: "",
                type: "decimal",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__danweihuansuanlv",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 1,
                label: "单位换算率",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 2,
                express:
                  "=choice({c__jiliangdanwei}=='KG',division({quantity},{c__danzhong}),{c__jiliangdanwei}=='kg',division({quantity},{c__danzhong}),{quantity})*choice({c__danweihuansuanlv}<0.00001,1,{c__danweihuansuanlv})",
                type: "decimal",
                compute: true,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__jibenshuliang",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 2,
                label: "基本数量",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 2,
                express: "",
                type: "money",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: false,
                canUpdate: false,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "unitPrice",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "单价",
                canCreate: false,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 2,
                express: "={c__jibenshuliang}*{unitPrice}",
                type: "money",
                compute: true,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: false,
                canUpdate: false,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "amount",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: true,
                length: 0,
                label: "金额",
                canCreate: false,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 2,
                express: "",
                type: "decimal",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: false,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__yiruku",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "已出库",
                canCreate: false,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 2,
                express: "=sub({c__jibenshuliang},{c__yiruku})",
                type: "decimal",
                compute: true,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__weiruku",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "未出库",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__bianhao",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__chanpinBOMdan",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields:
                  "c__bianhao,c__zhuwuliao,c__chanpinbianma,c__zhuwuliaoguige,c__banbenhao",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: "",
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "产品BOM",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "e__wlmxd",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "textarea",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "remark",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "附注",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
        ],
        title: "",
      },
    ],
    detailMulti: [],
    detailLayout: [
      {
        isShowFieldName: "false",
        useEmptyJudgment: "",
        useDeleteTips: "",
        isSpread: "false",
        lastId: "",
        id: "605555",
        packUpDetail: false,
        rows: [
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__bianma",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "productId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields:
                  "c__bianma,productName,c__guigexinghao,c__kucunshuliang",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: {
                  children: [],
                  filters: [
                    {
                      fieldName: "status",
                      type: "picklist",
                      filterType: "AND",
                      value: "0",
                      operator: "<>",
                    },
                  ],
                  type: "AND",
                },
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "产品编码",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "Product",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "money",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: false,
                canUpdate: false,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "unitPrice",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "单价",
                canCreate: false,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "undefined",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "picklist",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "units",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "类型",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "undefined",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [],
          },
          {
            cells: [],
          },
        ],
        title: "",
      },
    ],
    detailEntityName: "SalesOrderDetail",
    detailPickList: [
      {
        fieldName: "units",
        options: [
          {
            isDefault: "N",
            lable: "业务下单",
            value: "0",
          },
          {
            isDefault: "N",
            lable: "服务下单",
            value: "1",
          },
        ],
      },
    ],
  },
  isUseAuditFlow: false,
  pickList: [
    {
      fieldName: "orderType",
      options: [
        {
          isDefault: "Y",
          lable: "A类",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "C类",
          value: "1",
        },
        {
          isDefault: "N",
          lable: "B类",
          value: "3",
        },
      ],
    },
    {
      fieldName: "jihuijindugengxin",
      options: [
        {
          isDefault: "Y",
          lable: "赢单",
          value: "0",
        },
      ],
    },
    {
      fieldName: "isdeliver",
      options: [
        {
          isDefault: "Y",
          lable: "未投放",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "已投放",
          value: "1",
        },
      ],
    },
  ],
  areas: [
    {
      isShowFieldName: "",
      useEmptyJudgment: "",
      useDeleteTips: "",
      isSpread: "false",
      lastId: "",
      id: "infoAreadefault_drop",
      packUpDetail: true,
      rows: [
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "accountName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "req",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "accountId",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "c__NO,accountName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "客户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "Account",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "autonumber",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__NOM",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "单据编号",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__lianxiren",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "联系人",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "phone",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderName",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 50,
              label: "联系手机",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "$NOW$",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "req",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderDate",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 3,
              label: "日期",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__kehudingdanhao",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "客户订单号",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__jiaohuoriqi",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 3,
              label: "交货日期",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "textarea",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "remark",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "备注",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "attachment",
              compute: false,
              attachmentSizeLimit: "50",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__fujian",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "附件",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picture",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__tupian",
              allowUpload: true,
              enableRepeatMust: false,
              pictureSize: "small",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: true,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "图片（合同）",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
      ],
      title: "订单信息",
    },
  ],
  listAreas: [
    {
      isShowFieldName: "true",
      useEmptyJudgment: "",
      useDeleteTips: "",
      isSpread: "false",
      lastId: "",
      id: "595555",
      packUpDetail: false,
      rows: [
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "accountName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "accountId",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "c__NO,accountName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "客户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "Account",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__lianxiren",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "联系人",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "undefined",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "phone",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderName",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 50,
              label: "联系手机",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "undefined",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "$NOW$",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderDate",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 3,
              label: "日期",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "undefined",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "money",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: false,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "total",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "总金额",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "undefined",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
      ],
      title: "",
    },
  ],
  detailLayoutId: "209-c55f1a0d-98aa-4e5f-bbc1-2899b452665c",
  isUseShare: false,
  layoutId: "209-320acee1-3dcd-49f2-a8e9-9c948e896941",
  multi: [],
};

// 用户字段
export const userNameField = "owningUser";
