export const mobileLayout = {
  hasDetail: {
    detailEntityLabel: "订单明细",
    detailInfoAreas: [
      {
        isShowFieldName: "",
        useEmptyJudgment: "true",
        useDeleteTips: "true",
        isSpread: "false",
        lastId: "",
        id: "infoAreadefault_drop",
        packUpDetail: false,
        rows: [
          {
            cells: [
              {
                defaultValue: "016-c0742863-c11b-48a7-9dc5-0500d1d717f3",
                docSelectField: "",
                precision: 0,
                nameField: "label",
                express: "",
                type: "reference",
                subjectType: "SUBJECT",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "subjectId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "300",
                showFields: "label",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: [
                  {
                    fieldName: "childLength",
                    type: "int",
                    filterType: "AND",
                    value: 0,
                    operator: "=",
                  },
                  {
                    fieldName: "type",
                    type: "text",
                    filterType: "AND",
                    value: "SUBJECT",
                    operator: "=",
                  },
                ],
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "分类",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "Subject",
                allowUploadAttachment: false,
                defaultValueLabel: "成品类",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "text",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__chanpinbianma",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 255,
                label: "产品编码",
                canCreate: true,
                rows: 3,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "productName",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "productId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields:
                  "subjectId,productName,c__kucunshuliang,standardPrice,c__jibendanwei,remark",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: "",
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "产品名称",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "Product",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                nameField: "c__danweimingcheng",
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__jibendanwei",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                showFields: "c__danweimingcheng",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                referenceFilterCondition: "",
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "基本单位",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "e__dw",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "text",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "req",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__guigexinghao",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "1",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 255,
                label: "规格型号",
                canCreate: true,
                rows: 3,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 2,
                express: "",
                type: "decimal",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "quantity",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "数量",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
        ],
        title: "",
      },
    ],
    detailMulti: [
      {
        fieldName: "c__duoxuan",
        defaultValue: "1,2",
        options: "1,2,3,4,5",
        entity: "SalesOrderDetail",
      },
    ],
    detailLayout: [
      {
        isShowFieldName: "true",
        useEmptyJudgment: "",
        useDeleteTips: "",
        isSpread: "false",
        lastId: "",
        id: "605555",
        packUpDetail: false,
        rows: [
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "productId",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "产品名称",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "0",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "money",
                compute: true,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "unitPrice",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "单价",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: true,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "picklist",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "units",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 0,
                label: "产品类型",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "reference",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__jibendanwei",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 40,
                label: "基本单位",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
          {
            cells: [
              {
                defaultValue: "",
                docSelectField: "",
                precision: 0,
                express: "",
                type: "text",
                compute: false,
                attachmentSizeLimit: "",
                enableRepeat: false,
                options: "",
                allowUploadPicture: false,
                text: "",
                allowFrontEdit: false,
                fieldDefaultValue: "",
                req: "",
                readable: true,
                canUpdate: true,
                timeId: "",
                allowUploadProgress: false,
                selectionFinalLevel: false,
                showRecentRecord: "",
                list: "",
                lockRemoveLayout: false,
                name: "c__chanpinbianma",
                allowUpload: false,
                enableRepeatMust: false,
                pictureSize: "",
                desc: "",
                attachments: "",
                detailedWidth: "",
                pictures: "",
                lnglat: "",
                allowPhotograph: false,
                value: "",
                dataCascade: "",
                toMain: "",
                attendTotal: false,
                length: 255,
                label: "产品编码",
                canCreate: true,
                rows: 0,
                allowSelectLabels: false,
                onlyWebExpression: false,
                autoLocation: false,
                width: "311px",
                dynamicScript: "",
                loadDynamicScript: false,
                to: "",
                allowUploadAttachment: false,
                defaultValueLabel: "",
                entity: "SalesOrderDetail",
                canMultiple: false,
              },
            ],
          },
        ],
        title: "",
      },
    ],
    detailEntityName: "SalesOrderDetail",
    detailPickList: [
      {
        fieldName: "units",
        options: [
          {
            isDefault: "N",
            lable: "财务外包",
            value: "0",
          },
          {
            isDefault: "N",
            lable: "元",
            value: "1",
          },
          {
            isDefault: "N",
            lable: "PCS",
            value: "2",
          },
          {
            isDefault: "N",
            lable: "米",
            value: "3",
          },
          {
            isDefault: "N",
            lable: "KG",
            value: "4",
          },
        ],
      },
    ],
  },
  isUseAuditFlow: false,
  pickList: [
    {
      fieldName: "orderType",
      options: [
        {
          isDefault: "Y",
          lable: "A级代理",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "C级代理",
          value: "1",
        },
        {
          isDefault: "N",
          lable: "B级代理",
          value: "3",
        },
        {
          isDefault: "N",
          lable: "零售客户",
          value: "4",
        },
        {
          isDefault: "N",
          lable: "其它",
          value: "5",
        },
      ],
    },
    {
      fieldName: "jihuijindugengxin",
      options: [
        {
          isDefault: "Y",
          lable: "赢单",
          value: "0",
        },
      ],
    },
    {
      fieldName: "c__qianshuleixing",
      options: [
        {
          isDefault: "N",
          lable: "未签署",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "已签署",
          value: "1",
        },
        {
          isDefault: "Y",
          lable: "未生成合同",
          value: "2",
        },
      ],
    },
    {
      fieldName: "c__qianyuezhuangtai",
      options: [
        {
          isDefault: "Y",
          lable: "未生成合同",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "已生成合同",
          value: "1",
        },
        {
          isDefault: "N",
          lable: "已签约",
          value: "2",
        },
      ],
    },
    {
      fieldName: "c__shourumoshi",
      options: [
        {
          isDefault: "N",
          lable: "以订单记收入",
          value: "0",
        },
        {
          isDefault: "Y",
          lable: "以出库记收入",
          value: "1",
        },
      ],
    },
    {
      fieldName: "c__zhifuzhuangtai",
      options: [
        {
          isDefault: "N",
          lable: "未支付",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "已支付",
          value: "1",
        },
      ],
    },
    {
      fieldName: "isdeliver",
      options: [
        {
          isDefault: "Y",
          lable: "未投放",
          value: "0",
        },
        {
          isDefault: "N",
          lable: "已投放",
          value: "1",
        },
      ],
    },
  ],
  areas: [
    {
      isShowFieldName: "",
      useEmptyJudgment: "",
      useDeleteTips: "",
      isSpread: "false",
      lastId: "",
      id: "infoAreadefault_drop",
      packUpDetail: true,
      rows: [
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "accountName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "req",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "accountId",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "accountName,createdBy,createdOn",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "客户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "Account",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "autonumber",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__NOM",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "NO",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__lianxiren",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "联系人",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "phone",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderName",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 50,
              label: "联系手机",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "4",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picklist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "req",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderType",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "客户类型",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "016-2646aaa0-2f66-40e5-b314-ad0d40a50ca5",
              docSelectField: "",
              precision: 0,
              nameField: "label",
              express: "",
              type: "reference",
              subjectType: "xiaoshouleixing",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__xiaoshouleibie",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "label",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: [
                {
                  fieldName: "childLength",
                  type: "int",
                  filterType: "AND",
                  value: 0,
                  operator: "=",
                },
                {
                  fieldName: "type",
                  type: "text",
                  filterType: "AND",
                  value: "xiaoshouleixing",
                  operator: "=",
                },
              ],
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "销售类别",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "Subject",
              allowUploadAttachment: false,
              defaultValueLabel: "标准销售",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "$NOW$",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "req",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderDate",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 3,
              label: "日期",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 2,
              express: "",
              type: "money",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "total",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: true,
              length: 0,
              label: "总金额",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "0",
              docSelectField: "",
              precision: 2,
              express: "",
              type: "money",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "paid",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: true,
              length: 0,
              label: "已收款",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 2,
              express: "=choice(sub({total},{paid})<0,0,sub({total},{paid}))",
              type: "money",
              compute: true,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "unpaid",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "未收款",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picklist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__shourumoshi",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "收入模式",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "c__hesuanyuefen",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__hesuanyuefen",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "c__hesuanyuefen",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "核算月份",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "e__lrb",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "c__zhutimingcheng",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__hesuanzhuti",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "c__zhutimingcheng",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "核算主体",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "e__zcfz",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "attachment",
              compute: false,
              attachmentSizeLimit: "0",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__fujian",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "附件",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picklist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__zhifuzhuangtai",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "支付状态",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "3",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picklist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__qianshuleixing",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "签署类型",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "3",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "textarea",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "remark",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "1",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "备注",
              canCreate: true,
              rows: 2,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picture",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__tupian",
              allowUpload: true,
              enableRepeatMust: false,
              pictureSize: "small",
              desc: "建议用手机拍照上传进行电子归档",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: true,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "图片（合同）",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "c__fapiaobianhao",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__dianzifapiao",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "c__fapiaohao,c__fapiaobianhao",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "电子发票",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "outputinvoice",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "multi",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__duoxuan122",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "多选122",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__ceshiwenben",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "测试文本",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "userName",
              express: "",
              type: "referencelist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__ceshiduoxuanyonghu",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "userName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "测试多选用户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "User",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "multi",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__duoxuan1",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "多选1",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
      ],
      title: "布局一",
    },
    {
      isShowFieldName: "",
      useEmptyJudgment: "",
      useDeleteTips: "",
      isSpread: "true",
      lastId: "",
      id: "infoArea1547095265870",
      packUpDetail: true,
      rows: [
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "createdOn",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "2025-06-05 17:49:31",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 6,
              label: "创建时间",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "userName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "管理员",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "createdBy",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "userName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "027-4098f194-ec70-4acd-9d7a-b1ebf4ca7eb6",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "创建用户",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "User",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "userName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "管理员",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "owningUser",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "userName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "027-4098f194-ec70-4acd-9d7a-b1ebf4ca7eb6",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "所属用户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "User",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "name",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "公司总部",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "owningBusinessUnit",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "name",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "030-000000000000000000000000000000000000",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "所属部门",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "BusinessUnit",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "userName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "管理员",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "modifiedBy",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "userName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "027-4098f194-ec70-4acd-9d7a-b1ebf4ca7eb6",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "最近修改用户",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "User",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "modifiedOn",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "2025-06-05 17:49:31",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 6,
              label: "最近修改时间",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "picklist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__qianyuezhuangtai",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "签约状态",
              canCreate: true,
              rows: 3,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
      ],
      title: "相关信息",
    },
  ],
  listAreas: [
    {
      isShowFieldName: "true",
      useEmptyJudgment: "",
      useDeleteTips: "",
      isSpread: "false",
      lastId: "",
      id: "595555",
      packUpDetail: false,
      rows: [
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "accountName",
              express: "",
              type: "reference",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "accountId",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "accountName,createdBy,createdOn",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 0,
              label: "客户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "Account",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "text",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__lianxiren",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 255,
              label: "联系人",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "phone",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderName",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 50,
              label: "联系手机",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "$NOW$",
              docSelectField: "",
              precision: 0,
              express: "",
              type: "datetime",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "orderDate",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 3,
              label: "日期",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 2,
              express: "",
              type: "money",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: false,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "total",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: true,
              length: 0,
              label: "总金额",
              canCreate: false,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
        {
          cells: [
            {
              defaultValue: "",
              docSelectField: "",
              precision: 0,
              nameField: "userName",
              express: "",
              type: "referencelist",
              compute: false,
              attachmentSizeLimit: "",
              enableRepeat: false,
              options: "",
              allowUploadPicture: false,
              text: "",
              allowFrontEdit: false,
              fieldDefaultValue: "",
              req: "",
              readable: true,
              canUpdate: true,
              timeId: "",
              allowUploadProgress: false,
              selectionFinalLevel: false,
              showRecentRecord: "",
              list: "",
              lockRemoveLayout: false,
              name: "c__ceshiduoxuanyonghu",
              allowUpload: false,
              enableRepeatMust: false,
              pictureSize: "",
              desc: "",
              attachments: "",
              detailedWidth: "",
              showFields: "userName",
              pictures: "",
              lnglat: "",
              allowPhotograph: false,
              referenceFilterCondition: "",
              value: "",
              dataCascade: "",
              toMain: "",
              attendTotal: false,
              length: 40,
              label: "测试多选用户",
              canCreate: true,
              rows: 0,
              allowSelectLabels: false,
              onlyWebExpression: false,
              autoLocation: false,
              width: "311px",
              dynamicScript: "",
              loadDynamicScript: false,
              to: "User",
              allowUploadAttachment: false,
              defaultValueLabel: "",
              entity: "SalesOrder",
              canMultiple: false,
            },
          ],
        },
      ],
      title: "",
    },
  ],
  detailLayoutId: "209-5feef98f-8d51-4c3b-9d1e-4acfffc63f40",
  isUseShare: false,
  layoutId: "209-8c7e1e8c-504c-4731-8f69-daab156dc042",
  multi: [
    {
      fieldName: "c__duoxuan1",
      options: "1,2,3,4,5",
      entity: "SalesOrder",
    },
    {
      fieldName: "c__duoxuan122",
      defaultValue: "1,2",
      options: "1,2,3,4,5,324,2342,344,355,32434,44r,rerr",
      entity: "SalesOrder",
    },
  ],
};

// 引用类型
export const componentType = {
  reference: "reference",
};
