import { componentType } from "@/constants/mobile";
import { useMobileLayoutV2 } from "@/service/universal";
import { useAuth } from "@/store";
import { Area, Cell, MobileLayout, Row } from "@/types/mobile-layout";
import { useHttp } from "./http";
import { Menu } from "@/types/menu";
import { ACCOUNT, userNameField } from "@/constants";
import { User } from "@/types/user";

const mapRow = (area: Area) => ({
  ...area,
  rows: area.rows.flatMap((row: Row) => row.cells),
});

// 处理布局数据
export const handleLayout = (data: MobileLayout) => {
  const result = {
    ...data,
    areas: data.areas.map(mapRow),
    hasDetail: {
      ...data.hasDetail,
      detailInfoAreas: data.hasDetail.detailInfoAreas.map(mapRow),
      detailLayout: data.hasDetail.detailLayout.map(mapRow),
    },
    listAreas: data.listAreas.map(mapRow),
  };
  return result;
};

export type LayoutData = ReturnType<typeof handleLayout>;

type InitControlsParams = {
  entity: string;
  status: "add" | "edit";
  layout_id: string;
};

// 初始化布局
export const useInitControls = (params: InitControlsParams) => {
  const { entity, status, layout_id } = params;
  return useInitDetailLayout({ entity, status, layout_id, type: 1 });
};

type InitDetailLayout = {
  entity: string;
  type: number;
  status: string;
  layout_id: string;
  entityId?: string;
};

type Quote = {
  index: number;
  seq: number;
  nameField: Cell["nameField"];
  value: {
    id: Cell["nameField"];
  };
};

// 表单布局
export const useInitDetailLayout = (params: InitDetailLayout) => {
  const {
    data: layoutData,
    isLoading,
    error,
  } = useMobileLayoutV2({
    entity: params.entity,
    id: "",
    multipleLayoutId: params.layout_id,
  });

  return {
    layoutData,
    isLoading,
    error,
  };
};

// 初始化映射和级联映射
export const useInitEntityCascade = (params: Quote, layoutData: LayoutData) => {
  const { entity, name } = layoutData["areas"][params.index].rows[params.seq];

  // 明细模块名
  const detailEntityName = layoutData["hasDetail"]["detailEntityName"];
  if (!params.value.id) return layoutData;
};

export const getCurrentDate = (): string => {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
};

// 判断是否有值并且类型是reference或者是用户字段名
export const shouldMapReferenceField = (cell: Cell) => {
  return (
    (cell.defaultValue && cell.type === componentType.reference) ||
    cell.name === userNameField
  );
};

export const transformMenu = (menus: Menu[], user: User | null) => {
  // 1. 禁用列表和常量定义
  const disabledApp = [
    "EventCalendar",
    "FreshStatistics",
    "Analysis",
    "CallRecord",
    "ManageUser",
    "Report",
    "SmsMain",
    "Home",
    "manageUser",
    "e__kcydjl",
  ];
  const systemVersion = ["OCQ_JZZB", "OCQ_TYJZ", "OCQ_TYGJ", "OCQ_XMZB"];
  const jz = ["记账", "【记账】"];

  const moreChildren: Menu[] = [];

  const result = menus.reduce((acc: Menu[], menu) => {
    if (!menu?.children || menu.children.length === 0) {
      moreChildren.push(menu);
      return acc;
    }

    let newChildren = [...menu.children];

    const isSpecialVersion = systemVersion.includes(user?.systemVersion || "");
    const isJzMenu = jz.includes(menu.menuName);

    if (!isSpecialVersion && !isJzMenu) {
      const hasAccount = newChildren.some(
        (child) => child.menuName === "ACCOUNT"
      );
      const hasContacts = newChildren.some(
        (child) => child.menuName === "mailList"
      );

      if (hasAccount && !hasContacts) {
        newChildren.push({
          menuIcon: "tongxunlu",
          menuLabel: "通讯录",
          menuName: "mailList",
          menuUrl: "/acc/mailList",
        });
      }
    }

    acc.push({ ...menu, children: newChildren });
    return acc;
  }, []);

  if (moreChildren.length > 0) {
    result.push({
      menuIcon: "",
      menuUrl: "",
      menuName: "更多",
      menuLabel: "更多",
      children: moreChildren,
    });
  }

  return result;
};

export const menuList = [
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gzbg",
        menuName: "e__gzbg",
        menuLabel: "工作报告",
        name: "工作报告",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gzrw",
        menuName: "e__gzrw",
        menuLabel: "工作任务",
        name: "工作任务",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gjjl",
        menuName: "e__gjjl",
        menuLabel: "跟进记录",
        name: "跟进记录",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__swsp",
        menuName: "e__swsp",
        menuLabel: "事务审批",
        name: "事务审批",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "A046",
        menuUrl: "/genericEntity/showGrid?entity=e__zcsq",
        menuName: "e__zcsq",
        menuLabel: "支出申请",
        name: "支出申请",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconA046",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gzff",
        menuName: "e__gzff",
        menuLabel: "工资发放",
        name: "工资发放",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__plfk",
        menuName: "e__plfk",
        menuLabel: "合并付款",
        name: "合并付款",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ygda",
        menuName: "e__ygda",
        menuLabel: "员工档案",
        name: "员工档案",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yght",
        menuName: "e__yght",
        menuLabel: "员工合同",
        name: "员工合同",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/document/showGrid?entity=Document",
        menuName: "Document",
        menuLabel: "文件管理",
        name: "文件管理",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "办公",
    menuLabel: "办公",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "A015",
        menuUrl: "/genericEntity/showGrid?entity=e__yhzh",
        menuName: "e__yhzh",
        menuLabel: "资金账户",
        name: "资金账户",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA015",
        operate: "add",
      },
      {
        menuIcon: "E918",
        menuUrl: "/product/showGrid?entity=Product",
        menuName: "Product",
        menuLabel: "库存商品",
        name: "库存商品",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE918",
        operate: "add",
      },
      {
        menuIcon: "E8F7",
        menuUrl: "/genericEntity/showGrid?entity=e__zcdj",
        menuName: "e__zcdj",
        menuLabel: "其他资产",
        name: "其他资产",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE8F7",
        operate: "add",
      },
      {
        menuIcon: "A077",
        menuUrl: "/accountList/showGrid?entity=Account",
        menuName: "Account",
        menuLabel: "应收预收",
        name: "应收预收",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA077",
        operate: "add",
      },
      {
        menuIcon: "tongxunlu",
        menuLabel: "通讯录",
        menuName: "mailList",
        menuUrl: "/acc/mailList",
        name: "通讯录",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "icontongxunlu",
        operate: "add",
      },
      {
        menuIcon: "A037",
        menuUrl: "/genericEntity/showGrid?entity=e__gys",
        menuName: "e__gys",
        menuLabel: "应付预付",
        name: "应付预付",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA037",
        operate: "add",
      },
      {
        menuIcon: "A031",
        menuUrl: "/genericEntity/showGrid?entity=e__wldw",
        menuName: "e__wldw",
        menuLabel: "其他往来",
        name: "其他往来",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA031",
        operate: "add",
      },
      {
        menuIcon: "A036",
        menuUrl: "/genericEntity/showGrid?entity=e__skjl",
        menuName: "e__skjl",
        menuLabel: "回款记录",
        name: "回款记录",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA036",
        operate: "add",
      },
      {
        menuIcon: "A037",
        menuUrl: "/genericEntity/showGrid?entity=e__fkjl",
        menuName: "e__fkjl",
        menuLabel: "付款记录",
        name: "付款记录",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA037",
        operate: "add",
      },
      {
        menuIcon: "A031",
        menuUrl: "/genericEntity/showGrid?entity=e__zjtb",
        menuName: "e__zjtb",
        menuLabel: "资金调拨",
        name: "资金调拨",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA031",
        operate: "add",
      },
      {
        menuIcon: "A007",
        menuUrl: "/genericEntity/showGrid?entity=e__zjpd",
        menuName: "e__zjpd",
        menuLabel: "资金盘点",
        name: "资金盘点",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA007",
        operate: "add",
      },
      {
        menuIcon: "A042",
        menuUrl: "/genericEntity/showGrid?entity=e__zczj",
        menuName: "e__zczj",
        menuLabel: "分摊折旧",
        name: "分摊折旧",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA042",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zzdj",
        menuName: "e__zzdj",
        menuLabel: "转账单据",
        name: "转账单据",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__szlb",
        menuName: "e__szlb",
        menuLabel: "收支类别",
        name: "收支类别",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__bb",
        menuName: "e__bb",
        menuLabel: "货币类别",
        name: "货币类别",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "财务",
    menuLabel: "财务",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zckp",
        menuName: "e__zckp",
        menuLabel: "资产卡片",
        name: "资产卡片",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zcpd",
        menuName: "e__zcpd",
        menuLabel: "资产盘点",
        name: "资产盘点",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zcbf",
        menuName: "e__zcbf",
        menuLabel: "资产报废",
        name: "资产报废",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zczy",
        menuName: "e__zczy",
        menuLabel: "资产转移",
        name: "资产转移",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "资产",
    menuLabel: "资产",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__safl",
        menuName: "e__safl",
        menuLabel: "食安分类",
        name: "食安分类",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__dcwtd",
        menuName: "e__dcwtd",
        menuLabel: "食安标准",
        name: "食安标准",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__dcda",
        menuName: "e__dcda",
        menuLabel: "检查档案",
        name: "检查档案",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xmjcb",
        menuName: "e__xmjcb",
        menuLabel: "项目检查表",
        name: "项目检查表",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zggd",
        menuName: "e__zggd",
        menuLabel: "整改工单",
        name: "整改工单",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__pcry",
        menuName: "e__pcry",
        menuLabel: "陪餐人员",
        name: "陪餐人员",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__myddcb",
        menuName: "e__myddcb",
        menuLabel: "满意度调查表",
        name: "满意度调查表",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "审计督察",
    menuLabel: "督察",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl:
          "/homeDataBoard?module=HomeDataBoard&moduleId=170-11b4fe41-4557-42b0-8c0f-f88442572b55",
        menuName: "Link-Url",
        menuLabel: "财务看板",
        name: "财务看板",
        prevPeriod: "",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zcfz",
        menuName: "e__zcfz",
        menuLabel: "核算主体",
        name: "核算主体",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "A044",
        menuUrl: "/genericEntity/showGrid?entity=e__lrb",
        menuName: "e__lrb",
        menuLabel: "核算月份",
        name: "核算月份",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA044",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__hsxm",
        menuName: "e__hsxm",
        menuLabel: "核算项目",
        name: "核算项目",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__hsbm",
        menuName: "e__hsbm",
        menuLabel: "核算部门",
        name: "核算部门",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E801",
        menuUrl: "/genericEntity/showGrid?entity=e__ys",
        menuName: "e__ys",
        menuLabel: "成本预算",
        name: "成本预算",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE801",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl:
          "/seniorSetting/moduleManagerment/getLayoutById?layoutId=209-022d095f-f251-4786-9418-a87b4d955db2&layoutType=3",
        menuName: "layoutId:209-022d095f-f251-4786-9418-a87b4d955db2",
        menuLabel: "财务简报",
        name: "财务简报",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl:
          "/seniorSetting/moduleManagerment/getLayoutById?layoutId=209-12121ee1-20e1-4b7a-b4de-f8a7e7c4521c&layoutType=3",
        menuName: "layoutId:209-12121ee1-20e1-4b7a-b4de-f8a7e7c4521c",
        menuLabel: "经营报告",
        name: "经营报告",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cgdz",
        menuName: "e__cgdz",
        menuLabel: "采购对账",
        name: "采购对账",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xsdz",
        menuName: "e__xsdz",
        menuLabel: "销售对账",
        name: "销售对账",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "A033",
        menuUrl: "/genericEntity/showGrid?entity=e__szmx",
        menuName: "e__szmx",
        menuLabel: "资金收支明细",
        name: "资金收支明细",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA033",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ysmxb",
        menuName: "e__ysmxb",
        menuLabel: "销售应收明细",
        name: "销售应收明细",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yfmx",
        menuName: "e__yfmx",
        menuLabel: "采购应付明细",
        name: "采购应付明细",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__qtysmx",
        menuName: "e__qtysmx",
        menuLabel: "其他应收明细",
        name: "其他应收明细",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__qtyfmx",
        menuName: "e__qtyfmx",
        menuLabel: "其他应付明细",
        name: "其他应付明细",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__hsyftjb",
        menuName: "e__hsyftjb",
        menuLabel: "核算月份统计",
        name: "核算月份统计",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zhszyftjb",
        menuName: "e__zhszyftjb",
        menuLabel: "账户收支统计",
        name: "账户收支统计",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "报表",
    menuLabel: "报表",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zhgl",
        menuName: "e__zhgl",
        menuLabel: "账号管理",
        name: "账号管理",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zhsyjl",
        menuName: "e__zhsyjl",
        menuLabel: "账号使用记录",
        name: "账号使用记录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__czjl",
        menuName: "e__czjl",
        menuLabel: "充值记录",
        name: "充值记录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yzgl",
        menuName: "e__yzgl",
        menuLabel: "印章管理",
        name: "印章管理",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yzsysq",
        menuName: "e__yzsysq",
        menuLabel: "印章使用申请",
        name: "印章使用申请",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yzzx",
        menuName: "e__yzzx",
        menuLabel: "印章注销",
        name: "印章注销",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__bxtz",
        menuName: "e__bxtz",
        menuLabel: "保险台账",
        name: "保险台账",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gsajtz",
        menuName: "e__gsajtz",
        menuLabel: "工伤案件台账",
        name: "工伤案件台账",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__yght",
        menuName: "e__yght",
        menuLabel: "员工合同",
        name: "员工合同",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zzzs",
        menuName: "e__zzzs",
        menuLabel: "资质证书",
        name: "资质证书",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__nsjl",
        menuName: "e__nsjl",
        menuLabel: "年审记录",
        name: "年审记录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ldxx",
        menuName: "e__ldxx",
        menuLabel: "楼栋信息",
        name: "楼栋信息",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ssxx",
        menuName: "e__ssxx",
        menuLabel: "宿舍信息",
        name: "宿舍信息",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cwxx",
        menuName: "e__cwxx",
        menuLabel: "床位信息",
        name: "床位信息",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ssjl",
        menuName: "e__ssjl",
        menuLabel: "宿舍使用记录",
        name: "宿舍使用记录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "人事",
    menuLabel: "人事",
  },
  {
    menuIcon: "E24D",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zpxqtb",
        menuName: "e__zpxqtb",
        menuLabel: "招聘需求",
        name: "招聘需求",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zpjl",
        menuName: "e__zpjl",
        menuLabel: "招聘简历",
        name: "招聘简历",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "",
    menuLabel: "招聘",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E918",
        menuUrl: "/product/showGrid?entity=Product",
        menuName: "Product",
        menuLabel: "产品档案",
        name: "产品档案",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE918",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__wlmxd",
        menuName: "e__wlmxd",
        menuLabel: "产品BOM",
        name: "产品BOM",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/materialRequirement/getNewBOM",
        menuName: "newBOM",
        menuLabel: "BOM结构查询",
        name: "BOM结构查询",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__lbbm",
        menuName: "e__lbbm",
        menuLabel: "类别编码",
        name: "类别编码",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__wlxh",
        menuName: "e__wlxh",
        menuLabel: "物料型号",
        name: "物料型号",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__wlgg",
        menuName: "e__wlgg",
        menuLabel: "物料规格",
        name: "物料规格",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cdpp",
        menuName: "e__cdpp",
        menuLabel: "产地品牌",
        name: "产地品牌",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__dw",
        menuName: "e__dw",
        menuLabel: "计量单位",
        name: "计量单位",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "物料编码",
    menuLabel: "产品",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__srdj",
        menuName: "e__srdj",
        menuLabel: "收入日报",
        name: "收入日报",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "A077",
        menuUrl: "/accountList/showGrid?entity=Account",
        menuName: "Account",
        menuLabel: "客户",
        name: "客户",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconA077",
        operate: "add",
      },
      {
        menuIcon: "tongxunlu",
        menuLabel: "通讯录",
        menuName: "mailList",
        menuUrl: "/acc/mailList",
        name: "通讯录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "icontongxunlu",
        operate: "add",
      },
      {
        menuIcon: "E85D",
        menuUrl: "/salesOrder/showGrid?entity=SalesOrder",
        menuName: "SalesOrder",
        menuLabel: "销售订单",
        name: "销售订单",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE85D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=SalesOrderDetail",
        menuName: "Link-Url",
        menuLabel: "订单明细",
        name: "订单明细",
        prevPeriod: "",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E547",
        menuUrl: "/genericEntity/showGrid?entity=e__ckjl",
        menuName: "e__ckjl",
        menuLabel: "销售记录",
        name: "销售记录",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE547",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xsth",
        menuName: "e__xsth",
        menuLabel: "销售退货",
        name: "销售退货",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "A042",
        menuUrl: "/genericEntity/showGrid?entity=e__skdj",
        menuName: "e__skdj",
        menuLabel: "收款登记",
        name: "收款登记",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconA042",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xskpdj",
        menuName: "e__xskpdj",
        menuLabel: "销售开票登记",
        name: "销售开票登记",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "业务",
    menuLabel: "销售",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "A037",
        menuUrl: "/genericEntity/showGrid?entity=e__gys",
        menuName: "e__gys",
        menuLabel: "供应商",
        name: "供应商",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconA037",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cgdd",
        menuName: "e__cgdd",
        menuLabel: "采购订单",
        name: "采购订单",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cgddmx",
        menuName: "Link-Url",
        menuLabel: "采购明细",
        name: "采购明细",
        prevPeriod: "",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E558",
        menuUrl: "/genericEntity/showGrid?entity=e__rkjl",
        menuName: "e__rkjl",
        menuLabel: "采购记录",
        name: "采购记录",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE558",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cgth",
        menuName: "e__cgth",
        menuLabel: "采购退货",
        name: "采购退货",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "A046",
        menuUrl: "/genericEntity/showGrid?entity=e__zcsq",
        menuName: "e__zcsq",
        menuLabel: "支出申请",
        name: "支出申请",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconA046",
        operate: "empty",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__jxkpdj",
        menuName: "e__jxkpdj",
        menuLabel: "进项开票登记",
        name: "进项开票登记",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "采购",
    menuLabel: "采购",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E547",
        menuUrl: "/genericEntity/showGrid?entity=e__ckjl",
        menuName: "e__ckjl",
        menuLabel: "销售记录",
        name: "销售记录",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE547",
        operate: "add",
      },
      {
        menuIcon: "E558",
        menuUrl: "/genericEntity/showGrid?entity=e__rkjl",
        menuName: "e__rkjl",
        menuLabel: "采购记录",
        name: "采购记录",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE558",
        operate: "add",
      },
      {
        menuIcon: "A076",
        menuUrl: "/genericEntity/showGrid?entity=e__kctb",
        menuName: "e__kctb",
        menuLabel: "库存调拨",
        name: "库存调拨",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconA076",
        operate: "add",
      },
      {
        menuIcon: "E8A0",
        menuUrl: "/genericEntity/showGrid?entity=e__kcpd",
        menuName: "e__kcpd",
        menuLabel: "库存盘点",
        name: "库存盘点",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE8A0",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xtzhd",
        menuName: "e__xtzhd",
        menuLabel: "形态转换单",
        name: "形态转换单",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__qtck",
        menuName: "e__qtck",
        menuLabel: "其他出库",
        name: "其他出库",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__qtrk",
        menuName: "e__qtrk",
        menuLabel: "其他入库",
        name: "其他入库",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__xsth",
        menuName: "e__xsth",
        menuLabel: "销售退货",
        name: "销售退货",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cgth",
        menuName: "e__cgth",
        menuLabel: "采购退货",
        name: "采购退货",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__llck",
        menuName: "e__llck",
        menuLabel: "领料出库",
        name: "领料出库",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__wgrk",
        menuName: "e__wgrk",
        menuLabel: "完工入库",
        name: "完工入库",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cpkcb",
        menuName: "e__cpkcb",
        menuLabel: "库存明细表",
        name: "库存明细表",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__kcydb",
        menuName: "e__kcydb",
        menuLabel: "库存异动表",
        name: "库存异动表",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__ck",
        menuName: "e__ck",
        menuLabel: "仓库管理",
        name: "仓库管理",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__cw",
        menuName: "e__cw",
        menuLabel: "仓位管理",
        name: "仓位管理",
        bgColor: "rgba(87,141,217,.15)",
        color: "#578DD9",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "仓库 ",
    menuLabel: "仓库 ",
  },
  {
    menuIcon: "",
    menuUrl: "",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__khfwgd",
        menuName: "e__khfwgd",
        menuLabel: "服务工单",
        name: "服务工单",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__fwcl",
        menuName: "e__fwcl",
        menuLabel: "服务处理",
        name: "服务处理",
        bgColor: "rgba(242,98,85,.15)",
        color: "#F26255",
        img: "iconE24D",
        operate: "add",
      },
    ],
    menuName: "客户服务",
    menuLabel: "客户服务",
  },
  {
    menuLabel: "更多",
    menuName: "更多",
    children: [
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__khzyc",
        menuName: "e__khzyc",
        menuLabel: "客户资源池",
        name: "客户资源池",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__gysmyd",
        menuName: "e__gysmyd",
        menuLabel: "供应商满意度",
        name: "供应商满意度",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
      {
        menuIcon: "E24D",
        menuUrl: "/genericEntity/showGrid?entity=e__zjb",
        menuName: "e__zjb",
        menuLabel: "质检表",
        name: "质检表",
        bgColor: "rgba(255,134,75,.15)",
        color: "#FF864B",
        img: "iconE24D",
        operate: "add",
      },
    ],
  },
];
